# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.protocol.v1 import service_pb2 as loop_dot_protocol_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/protocol/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProtocolServiceStub:
    """Unary requests and responses are limited to 4 MiB by default. Domain layers
    impose stricter limits before allocation; numerical payloads remain external
    immutable artifacts.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProtocolInfo = channel.unary_unary(
                '/loop.protocol.v1.ProtocolService/GetProtocolInfo',
                request_serializer=loop_dot_protocol_dot_v1_dot_service__pb2.GetProtocolInfoRequest.SerializeToString,
                response_deserializer=loop_dot_protocol_dot_v1_dot_service__pb2.GetProtocolInfoResponse.FromString,
                _registered_method=True)


class ProtocolServiceServicer:
    """Unary requests and responses are limited to 4 MiB by default. Domain layers
    impose stricter limits before allocation; numerical payloads remain external
    immutable artifacts.
    """

    def GetProtocolInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtocolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProtocolInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProtocolInfo,
                    request_deserializer=loop_dot_protocol_dot_v1_dot_service__pb2.GetProtocolInfoRequest.FromString,
                    response_serializer=loop_dot_protocol_dot_v1_dot_service__pb2.GetProtocolInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.protocol.v1.ProtocolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.protocol.v1.ProtocolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProtocolService:
    """Unary requests and responses are limited to 4 MiB by default. Domain layers
    impose stricter limits before allocation; numerical payloads remain external
    immutable artifacts.
    """

    @staticmethod
    def GetProtocolInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.protocol.v1.ProtocolService/GetProtocolInfo',
            loop_dot_protocol_dot_v1_dot_service__pb2.GetProtocolInfoRequest.SerializeToString,
            loop_dot_protocol_dot_v1_dot_service__pb2.GetProtocolInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
