# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/protocol/v1/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/protocol/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eloop/protocol/v1/service.proto\x12\x10loop.protocol.v1\x1a\x14loop/v1/common.proto\"\x18\n\x16GetProtocolInfoRequest\"B\n\x17GetProtocolInfoResponse\x12\'\n\x08protocol\x18\x01 \x01(\x0b\x32\x15.loop.v1.ProtocolInfo2y\n\x0fProtocolService\x12\x66\n\x0fGetProtocolInfo\x12(.loop.protocol.v1.GetProtocolInfoRequest\x1a).loop.protocol.v1.GetProtocolInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.protocol.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROTOCOLINFOREQUEST']._serialized_start=74
  _globals['_GETPROTOCOLINFOREQUEST']._serialized_end=98
  _globals['_GETPROTOCOLINFORESPONSE']._serialized_start=100
  _globals['_GETPROTOCOLINFORESPONSE']._serialized_end=166
  _globals['_PROTOCOLSERVICE']._serialized_start=168
  _globals['_PROTOCOLSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
