# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.holdout.v1 import service_pb2 as loop_dot_holdout_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/holdout/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HoldoutServiceStub:
    """HoldoutService is deployed behind a separate capability interceptor and is
    absent from discovery and provider client allowlists.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordHoldoutApproval = channel.unary_unary(
                '/loop.holdout.v1.HoldoutService/RecordHoldoutApproval',
                request_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.RecordHoldoutApprovalRequest.SerializeToString,
                response_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.RecordHoldoutApprovalResponse.FromString,
                _registered_method=True)
        self.RequestHoldoutGrant = channel.unary_unary(
                '/loop.holdout.v1.HoldoutService/RequestHoldoutGrant',
                request_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.RequestHoldoutGrantRequest.SerializeToString,
                response_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.RequestHoldoutGrantResponse.FromString,
                _registered_method=True)
        self.ConsumeGrantAndEnqueueBacktest = channel.unary_unary(
                '/loop.holdout.v1.HoldoutService/ConsumeGrantAndEnqueueBacktest',
                request_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.ConsumeGrantAndEnqueueBacktestRequest.SerializeToString,
                response_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.ConsumeGrantAndEnqueueBacktestResponse.FromString,
                _registered_method=True)
        self.GetHoldoutPeriod = channel.unary_unary(
                '/loop.holdout.v1.HoldoutService/GetHoldoutPeriod',
                request_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutPeriodRequest.SerializeToString,
                response_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutPeriodResponse.FromString,
                _registered_method=True)
        self.GetHoldoutApprovalRecord = channel.unary_unary(
                '/loop.holdout.v1.HoldoutService/GetHoldoutApprovalRecord',
                request_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutApprovalRecordRequest.SerializeToString,
                response_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutApprovalRecordResponse.FromString,
                _registered_method=True)
        self.GetHoldoutGrant = channel.unary_unary(
                '/loop.holdout.v1.HoldoutService/GetHoldoutGrant',
                request_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutGrantRequest.SerializeToString,
                response_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutGrantResponse.FromString,
                _registered_method=True)


class HoldoutServiceServicer:
    """HoldoutService is deployed behind a separate capability interceptor and is
    absent from discovery and provider client allowlists.
    """

    def RecordHoldoutApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHoldoutGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeGrantAndEnqueueBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHoldoutPeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHoldoutApprovalRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHoldoutGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HoldoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordHoldoutApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordHoldoutApproval,
                    request_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.RecordHoldoutApprovalRequest.FromString,
                    response_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.RecordHoldoutApprovalResponse.SerializeToString,
            ),
            'RequestHoldoutGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHoldoutGrant,
                    request_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.RequestHoldoutGrantRequest.FromString,
                    response_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.RequestHoldoutGrantResponse.SerializeToString,
            ),
            'ConsumeGrantAndEnqueueBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeGrantAndEnqueueBacktest,
                    request_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.ConsumeGrantAndEnqueueBacktestRequest.FromString,
                    response_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.ConsumeGrantAndEnqueueBacktestResponse.SerializeToString,
            ),
            'GetHoldoutPeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoldoutPeriod,
                    request_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutPeriodRequest.FromString,
                    response_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutPeriodResponse.SerializeToString,
            ),
            'GetHoldoutApprovalRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoldoutApprovalRecord,
                    request_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutApprovalRecordRequest.FromString,
                    response_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutApprovalRecordResponse.SerializeToString,
            ),
            'GetHoldoutGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoldoutGrant,
                    request_deserializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutGrantRequest.FromString,
                    response_serializer=loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutGrantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.holdout.v1.HoldoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.holdout.v1.HoldoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HoldoutService:
    """HoldoutService is deployed behind a separate capability interceptor and is
    absent from discovery and provider client allowlists.
    """

    @staticmethod
    def RecordHoldoutApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.holdout.v1.HoldoutService/RecordHoldoutApproval',
            loop_dot_holdout_dot_v1_dot_service__pb2.RecordHoldoutApprovalRequest.SerializeToString,
            loop_dot_holdout_dot_v1_dot_service__pb2.RecordHoldoutApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHoldoutGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.holdout.v1.HoldoutService/RequestHoldoutGrant',
            loop_dot_holdout_dot_v1_dot_service__pb2.RequestHoldoutGrantRequest.SerializeToString,
            loop_dot_holdout_dot_v1_dot_service__pb2.RequestHoldoutGrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeGrantAndEnqueueBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.holdout.v1.HoldoutService/ConsumeGrantAndEnqueueBacktest',
            loop_dot_holdout_dot_v1_dot_service__pb2.ConsumeGrantAndEnqueueBacktestRequest.SerializeToString,
            loop_dot_holdout_dot_v1_dot_service__pb2.ConsumeGrantAndEnqueueBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHoldoutPeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.holdout.v1.HoldoutService/GetHoldoutPeriod',
            loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutPeriodRequest.SerializeToString,
            loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutPeriodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHoldoutApprovalRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.holdout.v1.HoldoutService/GetHoldoutApprovalRecord',
            loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutApprovalRecordRequest.SerializeToString,
            loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutApprovalRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHoldoutGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.holdout.v1.HoldoutService/GetHoldoutGrant',
            loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutGrantRequest.SerializeToString,
            loop_dot_holdout_dot_v1_dot_service__pb2.GetHoldoutGrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
