# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.jobs.v1 import service_pb2 as loop_dot_jobs_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/jobs/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJob = channel.unary_unary(
                '/loop.jobs.v1.JobService/GetJob',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.AcquireJobLease = channel.unary_unary(
                '/loop.jobs.v1.JobService/AcquireJobLease',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseResponse.FromString,
                _registered_method=True)
        self.HeartbeatJobLease = channel.unary_unary(
                '/loop.jobs.v1.JobService/HeartbeatJobLease',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseResponse.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/loop.jobs.v1.JobService/CompleteJob',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/loop.jobs.v1.JobService/CancelJob',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class JobServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireJobLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatJobLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobResponse.SerializeToString,
            ),
            'AcquireJobLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireJobLease,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseResponse.SerializeToString,
            ),
            'HeartbeatJobLease': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatJobLease,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseResponse.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.jobs.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.jobs.v1.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/GetJob',
            loop_dot_jobs_dot_v1_dot_service__pb2.GetJobRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireJobLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/AcquireJobLease',
            loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatJobLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/HeartbeatJobLease',
            loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/CompleteJob',
            loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/CancelJob',
            loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
