# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.jobs.v1 import service_pb2 as loop_dot_jobs_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/jobs/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJob = channel.unary_unary(
                '/loop.jobs.v1.JobService/GetJob',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.AcquireJobLease = channel.unary_unary(
                '/loop.jobs.v1.JobService/AcquireJobLease',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseResponse.FromString,
                _registered_method=True)
        self.HeartbeatJobLease = channel.unary_unary(
                '/loop.jobs.v1.JobService/HeartbeatJobLease',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseResponse.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/loop.jobs.v1.JobService/CompleteJob',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/loop.jobs.v1.JobService/CancelJob',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.PrepareJobArtifacts = channel.unary_unary(
                '/loop.jobs.v1.JobService/PrepareJobArtifacts',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.PrepareJobArtifactsRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.PrepareJobArtifactsResponse.FromString,
                _registered_method=True)
        self.EvaluateFactor = channel.unary_unary(
                '/loop.jobs.v1.JobService/EvaluateFactor',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.EvaluateFactorRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.EvaluateFactorResponse.FromString,
                _registered_method=True)
        self.ExecuteBacktest = channel.unary_unary(
                '/loop.jobs.v1.JobService/ExecuteBacktest',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteBacktestRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteBacktestResponse.FromString,
                _registered_method=True)
        self.ExecuteReconciliation = channel.unary_unary(
                '/loop.jobs.v1.JobService/ExecuteReconciliation',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteReconciliationRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteReconciliationResponse.FromString,
                _registered_method=True)
        self.ReadReconciliation = channel.unary_unary(
                '/loop.jobs.v1.JobService/ReadReconciliation',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadReconciliationRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadReconciliationResponse.FromString,
                _registered_method=True)
        self.ExecuteStatistics = channel.unary_unary(
                '/loop.jobs.v1.JobService/ExecuteStatistics',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteStatisticsRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteStatisticsResponse.FromString,
                _registered_method=True)
        self.ReadStatistics = channel.unary_unary(
                '/loop.jobs.v1.JobService/ReadStatistics',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadStatisticsRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadStatisticsResponse.FromString,
                _registered_method=True)
        self.ReadBacktest = channel.unary_unary(
                '/loop.jobs.v1.JobService/ReadBacktest',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadBacktestRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadBacktestResponse.FromString,
                _registered_method=True)
        self.ExportBacktest = channel.unary_unary(
                '/loop.jobs.v1.JobService/ExportBacktest',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExportBacktestRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExportBacktestResponse.FromString,
                _registered_method=True)
        self.DecideFactor = channel.unary_unary(
                '/loop.jobs.v1.JobService/DecideFactor',
                request_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.DecideFactorRequest.SerializeToString,
                response_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.DecideFactorResponse.FromString,
                _registered_method=True)


class JobServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireJobLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatJobLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareJobArtifacts(self, request, context):
        """Materializes a read-only, job-scoped view; payload bytes never cross RPC.
        Protected access additionally requires a lease-bound capability in metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateFactor(self, request, context):
        """Execute a deployment-selected numerical worker on an existing development
        lease. The caller cannot submit output bytes, code, paths or worker identity.
        Same command replay verifies immutable output instead of recomputing it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBacktest(self, request, context):
        """Execute only the pinned installed portfolio producer on a development
        lease. Metrics, trial subsets, worker paths and holdouts are not accepted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteReconciliation(self, request, context):
        """Reconstruct a registered development primary and run both pinned independent
        validators under this reconciliation job's lease. No caller result import.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadReconciliation(self, request, context):
        """Revalidate primary and independent evidence before returning its report.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStatistics(self, request, context):
        """Compute from the complete authorized development trial registry. The report
        recipe and policy are frozen in an existing Report job; no subset is accepted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadStatistics(self, request, context):
        """Revalidate complete registry membership and original numerical evidence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBacktest(self, request, context):
        """Reconstruct current evidence; historical job metadata is not a freshness claim.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportBacktest(self, request, context):
        """Audit metadata release before responding; artifact access remains separate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecideFactor(self, request, context):
        """Ordinary admission/readmission share the same durable command. Missing
        independent validation remains a dependency failure, never an approval.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.GetJobResponse.SerializeToString,
            ),
            'AcquireJobLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireJobLease,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseResponse.SerializeToString,
            ),
            'HeartbeatJobLease': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatJobLease,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseResponse.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobResponse.SerializeToString,
            ),
            'PrepareJobArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareJobArtifacts,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.PrepareJobArtifactsRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.PrepareJobArtifactsResponse.SerializeToString,
            ),
            'EvaluateFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateFactor,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.EvaluateFactorRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.EvaluateFactorResponse.SerializeToString,
            ),
            'ExecuteBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBacktest,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteBacktestRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteBacktestResponse.SerializeToString,
            ),
            'ExecuteReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteReconciliation,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteReconciliationRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteReconciliationResponse.SerializeToString,
            ),
            'ReadReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadReconciliation,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadReconciliationRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadReconciliationResponse.SerializeToString,
            ),
            'ExecuteStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStatistics,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteStatisticsRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteStatisticsResponse.SerializeToString,
            ),
            'ReadStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadStatistics,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadStatisticsRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadStatisticsResponse.SerializeToString,
            ),
            'ReadBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBacktest,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadBacktestRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ReadBacktestResponse.SerializeToString,
            ),
            'ExportBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportBacktest,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExportBacktestRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.ExportBacktestResponse.SerializeToString,
            ),
            'DecideFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.DecideFactor,
                    request_deserializer=loop_dot_jobs_dot_v1_dot_service__pb2.DecideFactorRequest.FromString,
                    response_serializer=loop_dot_jobs_dot_v1_dot_service__pb2.DecideFactorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.jobs.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.jobs.v1.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/GetJob',
            loop_dot_jobs_dot_v1_dot_service__pb2.GetJobRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireJobLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/AcquireJobLease',
            loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.AcquireJobLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatJobLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/HeartbeatJobLease',
            loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.HeartbeatJobLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/CompleteJob',
            loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.CompleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/CancelJob',
            loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareJobArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/PrepareJobArtifacts',
            loop_dot_jobs_dot_v1_dot_service__pb2.PrepareJobArtifactsRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.PrepareJobArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/EvaluateFactor',
            loop_dot_jobs_dot_v1_dot_service__pb2.EvaluateFactorRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.EvaluateFactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ExecuteBacktest',
            loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteBacktestRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ExecuteReconciliation',
            loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteReconciliationRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ReadReconciliation',
            loop_dot_jobs_dot_v1_dot_service__pb2.ReadReconciliationRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ReadReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ExecuteStatistics',
            loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteStatisticsRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ExecuteStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ReadStatistics',
            loop_dot_jobs_dot_v1_dot_service__pb2.ReadStatisticsRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ReadStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ReadBacktest',
            loop_dot_jobs_dot_v1_dot_service__pb2.ReadBacktestRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ReadBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/ExportBacktest',
            loop_dot_jobs_dot_v1_dot_service__pb2.ExportBacktestRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.ExportBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecideFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.jobs.v1.JobService/DecideFactor',
            loop_dot_jobs_dot_v1_dot_service__pb2.DecideFactorRequest.SerializeToString,
            loop_dot_jobs_dot_v1_dot_service__pb2.DecideFactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
