# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.research.v1 import service_pb2 as loop_dot_research_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/research/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResearchServiceStub:
    """ResearchService accepts development inputs only. Implementations must
    validate each command and atomically insert a queued job; computation never
    runs inline. Durable insertion is implemented by loopd in Phase 3.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueFactorEvaluation = channel.unary_unary(
                '/loop.research.v1.ResearchService/EnqueueFactorEvaluation',
                request_serializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueFactorEvaluationRequest.SerializeToString,
                response_deserializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueFactorEvaluationResponse.FromString,
                _registered_method=True)
        self.EnqueueBacktest = channel.unary_unary(
                '/loop.research.v1.ResearchService/EnqueueBacktest',
                request_serializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueBacktestRequest.SerializeToString,
                response_deserializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueBacktestResponse.FromString,
                _registered_method=True)
        self.EnqueueReconciliation = channel.unary_unary(
                '/loop.research.v1.ResearchService/EnqueueReconciliation',
                request_serializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueReconciliationRequest.SerializeToString,
                response_deserializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueReconciliationResponse.FromString,
                _registered_method=True)


class ResearchServiceServicer:
    """ResearchService accepts development inputs only. Implementations must
    validate each command and atomically insert a queued job; computation never
    runs inline. Durable insertion is implemented by loopd in Phase 3.
    """

    def EnqueueFactorEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueReconciliation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueFactorEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueFactorEvaluation,
                    request_deserializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueFactorEvaluationRequest.FromString,
                    response_serializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueFactorEvaluationResponse.SerializeToString,
            ),
            'EnqueueBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueBacktest,
                    request_deserializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueBacktestRequest.FromString,
                    response_serializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueBacktestResponse.SerializeToString,
            ),
            'EnqueueReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueReconciliation,
                    request_deserializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueReconciliationRequest.FromString,
                    response_serializer=loop_dot_research_dot_v1_dot_service__pb2.EnqueueReconciliationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.research.v1.ResearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.research.v1.ResearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResearchService:
    """ResearchService accepts development inputs only. Implementations must
    validate each command and atomically insert a queued job; computation never
    runs inline. Durable insertion is implemented by loopd in Phase 3.
    """

    @staticmethod
    def EnqueueFactorEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.research.v1.ResearchService/EnqueueFactorEvaluation',
            loop_dot_research_dot_v1_dot_service__pb2.EnqueueFactorEvaluationRequest.SerializeToString,
            loop_dot_research_dot_v1_dot_service__pb2.EnqueueFactorEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.research.v1.ResearchService/EnqueueBacktest',
            loop_dot_research_dot_v1_dot_service__pb2.EnqueueBacktestRequest.SerializeToString,
            loop_dot_research_dot_v1_dot_service__pb2.EnqueueBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.research.v1.ResearchService/EnqueueReconciliation',
            loop_dot_research_dot_v1_dot_service__pb2.EnqueueReconciliationRequest.SerializeToString,
            loop_dot_research_dot_v1_dot_service__pb2.EnqueueReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
