# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/provider/v1/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/provider/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2
from loop.v1 import model_pb2 as loop_dot_v1_dot_model__pb2
from loop.v1 import stream_pb2 as loop_dot_v1_dot_stream__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eloop/provider/v1/service.proto\x12\x10loop.provider.v1\x1a\x14loop/v1/common.proto\x1a\x13loop/v1/model.proto\x1a\x14loop/v1/stream.proto\"l\n\x12InvokeModelRequest\x12(\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x17.loop.v1.CommandContext\x12,\n\ninvocation\x18\x02 \x01(\x0b\x32\x18.loop.v1.ModelInvocation\"?\n\x13InvokeModelResponse\x12(\n\x08response\x18\x01 \x01(\x0b\x32\x16.loop.v1.ModelResponse\"l\n\x12StreamModelRequest\x12(\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x17.loop.v1.CommandContext\x12,\n\ninvocation\x18\x02 \x01(\x0b\x32\x18.loop.v1.ModelInvocation\"?\n\x13StreamModelResponse\x12(\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x19.loop.v1.ModelStreamEvent2\xcb\x01\n\x0fProviderService\x12Z\n\x0bInvokeModel\x12$.loop.provider.v1.InvokeModelRequest\x1a%.loop.provider.v1.InvokeModelResponse\x12\\\n\x0bStreamModel\x12$.loop.provider.v1.StreamModelRequest\x1a%.loop.provider.v1.StreamModelResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.provider.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOKEMODELREQUEST']._serialized_start=117
  _globals['_INVOKEMODELREQUEST']._serialized_end=225
  _globals['_INVOKEMODELRESPONSE']._serialized_start=227
  _globals['_INVOKEMODELRESPONSE']._serialized_end=290
  _globals['_STREAMMODELREQUEST']._serialized_start=292
  _globals['_STREAMMODELREQUEST']._serialized_end=400
  _globals['_STREAMMODELRESPONSE']._serialized_start=402
  _globals['_STREAMMODELRESPONSE']._serialized_end=465
  _globals['_PROVIDERSERVICE']._serialized_start=468
  _globals['_PROVIDERSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
