# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.provider.v1 import service_pb2 as loop_dot_provider_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/provider/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProviderServiceStub:
    """ProviderService has no research-state or holdout imports. Provider plugins
    translate this typed model contract into native wire protocols.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeModel = channel.unary_unary(
                '/loop.provider.v1.ProviderService/InvokeModel',
                request_serializer=loop_dot_provider_dot_v1_dot_service__pb2.InvokeModelRequest.SerializeToString,
                response_deserializer=loop_dot_provider_dot_v1_dot_service__pb2.InvokeModelResponse.FromString,
                _registered_method=True)
        self.StreamModel = channel.unary_stream(
                '/loop.provider.v1.ProviderService/StreamModel',
                request_serializer=loop_dot_provider_dot_v1_dot_service__pb2.StreamModelRequest.SerializeToString,
                response_deserializer=loop_dot_provider_dot_v1_dot_service__pb2.StreamModelResponse.FromString,
                _registered_method=True)


class ProviderServiceServicer:
    """ProviderService has no research-state or holdout imports. Provider plugins
    translate this typed model contract into native wire protocols.
    """

    def InvokeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeModel,
                    request_deserializer=loop_dot_provider_dot_v1_dot_service__pb2.InvokeModelRequest.FromString,
                    response_serializer=loop_dot_provider_dot_v1_dot_service__pb2.InvokeModelResponse.SerializeToString,
            ),
            'StreamModel': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamModel,
                    request_deserializer=loop_dot_provider_dot_v1_dot_service__pb2.StreamModelRequest.FromString,
                    response_serializer=loop_dot_provider_dot_v1_dot_service__pb2.StreamModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.provider.v1.ProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.provider.v1.ProviderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderService:
    """ProviderService has no research-state or holdout imports. Provider plugins
    translate this typed model contract into native wire protocols.
    """

    @staticmethod
    def InvokeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.provider.v1.ProviderService/InvokeModel',
            loop_dot_provider_dot_v1_dot_service__pb2.InvokeModelRequest.SerializeToString,
            loop_dot_provider_dot_v1_dot_service__pb2.InvokeModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loop.provider.v1.ProviderService/StreamModel',
            loop_dot_provider_dot_v1_dot_service__pb2.StreamModelRequest.SerializeToString,
            loop_dot_provider_dot_v1_dot_service__pb2.StreamModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
