# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.audit.v1 import service_pb2 as loop_dot_audit_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/audit/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendAuditEvent = channel.unary_unary(
                '/loop.audit.v1.AuditService/AppendAuditEvent',
                request_serializer=loop_dot_audit_dot_v1_dot_service__pb2.AppendAuditEventRequest.SerializeToString,
                response_deserializer=loop_dot_audit_dot_v1_dot_service__pb2.AppendAuditEventResponse.FromString,
                _registered_method=True)
        self.GetAuditEvent = channel.unary_unary(
                '/loop.audit.v1.AuditService/GetAuditEvent',
                request_serializer=loop_dot_audit_dot_v1_dot_service__pb2.GetAuditEventRequest.SerializeToString,
                response_deserializer=loop_dot_audit_dot_v1_dot_service__pb2.GetAuditEventResponse.FromString,
                _registered_method=True)
        self.ListAuditEvents = channel.unary_unary(
                '/loop.audit.v1.AuditService/ListAuditEvents',
                request_serializer=loop_dot_audit_dot_v1_dot_service__pb2.ListAuditEventsRequest.SerializeToString,
                response_deserializer=loop_dot_audit_dot_v1_dot_service__pb2.ListAuditEventsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AppendAuditEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendAuditEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendAuditEvent,
                    request_deserializer=loop_dot_audit_dot_v1_dot_service__pb2.AppendAuditEventRequest.FromString,
                    response_serializer=loop_dot_audit_dot_v1_dot_service__pb2.AppendAuditEventResponse.SerializeToString,
            ),
            'GetAuditEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditEvent,
                    request_deserializer=loop_dot_audit_dot_v1_dot_service__pb2.GetAuditEventRequest.FromString,
                    response_serializer=loop_dot_audit_dot_v1_dot_service__pb2.GetAuditEventResponse.SerializeToString,
            ),
            'ListAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditEvents,
                    request_deserializer=loop_dot_audit_dot_v1_dot_service__pb2.ListAuditEventsRequest.FromString,
                    response_serializer=loop_dot_audit_dot_v1_dot_service__pb2.ListAuditEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.audit.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.audit.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppendAuditEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.audit.v1.AuditService/AppendAuditEvent',
            loop_dot_audit_dot_v1_dot_service__pb2.AppendAuditEventRequest.SerializeToString,
            loop_dot_audit_dot_v1_dot_service__pb2.AppendAuditEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.audit.v1.AuditService/GetAuditEvent',
            loop_dot_audit_dot_v1_dot_service__pb2.GetAuditEventRequest.SerializeToString,
            loop_dot_audit_dot_v1_dot_service__pb2.GetAuditEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.audit.v1.AuditService/ListAuditEvents',
            loop_dot_audit_dot_v1_dot_service__pb2.ListAuditEventsRequest.SerializeToString,
            loop_dot_audit_dot_v1_dot_service__pb2.ListAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
