# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/audit/v1/service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/audit/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from loop.v1 import audit_pb2 as loop_dot_v1_dot_audit__pb2
from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bloop/audit/v1/service.proto\x12\rloop.audit.v1\x1a\x13loop/v1/audit.proto\x1a\x14loop/v1/common.proto\"\xcb\x02\n\x17\x41ppendAuditEventRequest\x12(\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x17.loop.v1.CommandContext\x12\"\n\x1a\x65xpected_previous_sequence\x18\x02 \x01(\x04\x12=\n\x1e\x65xpected_previous_event_sha256\x18\x03 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12$\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x14.loop.v1.AuditAction\x12$\n\x06target\x18\x05 \x01(\x0b\x32\x14.loop.v1.AuditTarget\x12&\n\x07payload\x18\x06 \x01(\x0b\x32\x15.loop.v1.AuditPayload\x12/\n\x0f\x61udit_ledger_id\x18\x07 \x01(\x0b\x32\x16.loop.v1.AuditLedgerId\">\n\x18\x41ppendAuditEventResponse\x12\"\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x13.loop.v1.AuditEvent\"E\n\x14GetAuditEventRequest\x12-\n\x0e\x61udit_event_id\x18\x01 \x01(\x0b\x32\x15.loop.v1.AuditEventId\";\n\x15GetAuditEventResponse\x12\"\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x13.loop.v1.AuditEvent\"\x93\x01\n\x16ListAuditEventsRequest\x12$\n\x06target\x18\x01 \x01(\x0b\x32\x14.loop.v1.AuditTarget\x12\"\n\x04page\x18\x02 \x01(\x0b\x32\x14.loop.v1.PageRequest\x12/\n\x0f\x61udit_ledger_id\x18\x03 \x01(\x0b\x32\x16.loop.v1.AuditLedgerId\"_\n\x17ListAuditEventsResponse\x12#\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x13.loop.v1.AuditEvent\x12\x1f\n\x04page\x18\x02 \x01(\x0b\x32\x11.loop.v1.PageInfo2\xb1\x02\n\x0c\x41uditService\x12\x63\n\x10\x41ppendAuditEvent\x12&.loop.audit.v1.AppendAuditEventRequest\x1a\'.loop.audit.v1.AppendAuditEventResponse\x12Z\n\rGetAuditEvent\x12#.loop.audit.v1.GetAuditEventRequest\x1a$.loop.audit.v1.GetAuditEventResponse\x12`\n\x0fListAuditEvents\x12%.loop.audit.v1.ListAuditEventsRequest\x1a&.loop.audit.v1.ListAuditEventsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.audit.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDAUDITEVENTREQUEST']._serialized_start=90
  _globals['_APPENDAUDITEVENTREQUEST']._serialized_end=421
  _globals['_APPENDAUDITEVENTRESPONSE']._serialized_start=423
  _globals['_APPENDAUDITEVENTRESPONSE']._serialized_end=485
  _globals['_GETAUDITEVENTREQUEST']._serialized_start=487
  _globals['_GETAUDITEVENTREQUEST']._serialized_end=556
  _globals['_GETAUDITEVENTRESPONSE']._serialized_start=558
  _globals['_GETAUDITEVENTRESPONSE']._serialized_end=617
  _globals['_LISTAUDITEVENTSREQUEST']._serialized_start=620
  _globals['_LISTAUDITEVENTSREQUEST']._serialized_end=767
  _globals['_LISTAUDITEVENTSRESPONSE']._serialized_start=769
  _globals['_LISTAUDITEVENTSRESPONSE']._serialized_end=864
  _globals['_AUDITSERVICE']._serialized_start=867
  _globals['_AUDITSERVICE']._serialized_end=1172
# @@protoc_insertion_point(module_scope)
