# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.runs.v1 import service_pb2 as loop_dot_runs_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/runs/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunServiceStub:
    """RunService is owned by the authenticated Human operator. The server resolves
    the frozen plan and Agent executor; callers cannot supply child job inputs,
    replacement models, budgets, datasets, or protected research capabilities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRun = channel.unary_unary(
                '/loop.runs.v1.RunService/StartRun',
                request_serializer=loop_dot_runs_dot_v1_dot_service__pb2.StartRunRequest.SerializeToString,
                response_deserializer=loop_dot_runs_dot_v1_dot_service__pb2.StartRunResponse.FromString,
                _registered_method=True)
        self.StepRun = channel.unary_unary(
                '/loop.runs.v1.RunService/StepRun',
                request_serializer=loop_dot_runs_dot_v1_dot_service__pb2.StepRunRequest.SerializeToString,
                response_deserializer=loop_dot_runs_dot_v1_dot_service__pb2.StepRunResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/loop.runs.v1.RunService/GetRun',
                request_serializer=loop_dot_runs_dot_v1_dot_service__pb2.GetRunRequest.SerializeToString,
                response_deserializer=loop_dot_runs_dot_v1_dot_service__pb2.GetRunResponse.FromString,
                _registered_method=True)


class RunServiceServicer:
    """RunService is owned by the authenticated Human operator. The server resolves
    the frozen plan and Agent executor; callers cannot supply child job inputs,
    replacement models, budgets, datasets, or protected research capabilities.
    """

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepRun(self, request, context):
        """Executes the current child and advances at most one durable round. The
        original command key never authorizes a second advancement on replay.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Owner-scoped observation is available without a live execution plan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=loop_dot_runs_dot_v1_dot_service__pb2.StartRunRequest.FromString,
                    response_serializer=loop_dot_runs_dot_v1_dot_service__pb2.StartRunResponse.SerializeToString,
            ),
            'StepRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StepRun,
                    request_deserializer=loop_dot_runs_dot_v1_dot_service__pb2.StepRunRequest.FromString,
                    response_serializer=loop_dot_runs_dot_v1_dot_service__pb2.StepRunResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=loop_dot_runs_dot_v1_dot_service__pb2.GetRunRequest.FromString,
                    response_serializer=loop_dot_runs_dot_v1_dot_service__pb2.GetRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.runs.v1.RunService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.runs.v1.RunService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunService:
    """RunService is owned by the authenticated Human operator. The server resolves
    the frozen plan and Agent executor; callers cannot supply child job inputs,
    replacement models, budgets, datasets, or protected research capabilities.
    """

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.runs.v1.RunService/StartRun',
            loop_dot_runs_dot_v1_dot_service__pb2.StartRunRequest.SerializeToString,
            loop_dot_runs_dot_v1_dot_service__pb2.StartRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.runs.v1.RunService/StepRun',
            loop_dot_runs_dot_v1_dot_service__pb2.StepRunRequest.SerializeToString,
            loop_dot_runs_dot_v1_dot_service__pb2.StepRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.runs.v1.RunService/GetRun',
            loop_dot_runs_dot_v1_dot_service__pb2.GetRunRequest.SerializeToString,
            loop_dot_runs_dot_v1_dot_service__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
