# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/v1/artifact.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/v1/artifact.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16loop/v1/artifact.proto\x12\x07loop.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14loop/v1/common.proto\"f\n\x17\x41rtifactSchemaReference\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\r\x12,\n\rschema_sha256\x18\x03 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\"\xca\x02\n\x0b\x41rtifactRef\x12(\n\x0b\x61rtifact_id\x18\x01 \x01(\x0b\x32\x13.loop.v1.ArtifactId\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12%\n\x06sha256\x18\x03 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12\x30\n\x06schema\x18\x04 \x01(\x0b\x32 .loop.v1.ArtifactSchemaReference\x12\x12\n\nmedia_type\x18\x05 \x01(\t\x12\x11\n\tbyte_size\x18\x06 \x01(\x04\x12\x16\n\trow_count\x18\x07 \x01(\x04H\x00\x88\x01\x01\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x0fmanifest_sha256\x18\t \x01(\x0b\x32\x15.loop.v1.Sha256DigestB\x0c\n\n_row_countb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.v1.artifact_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTIFACTSCHEMAREFERENCE']._serialized_start=90
  _globals['_ARTIFACTSCHEMAREFERENCE']._serialized_end=192
  _globals['_ARTIFACTREF']._serialized_start=195
  _globals['_ARTIFACTREF']._serialized_end=525
# @@protoc_insertion_point(module_scope)
