# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/v1/development_data.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/v1/development_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eloop/v1/development_data.proto\x12\x07loop.v1\x1a\x14loop/v1/common.proto\"x\n\x1b\x44\x65velopmentDatasetReference\x12)\n\x0csnapshot_ids\x18\x01 \x03(\x0b\x32\x13.loop.v1.SnapshotId\x12.\n\x0fmanifest_sha256\x18\x02 \x01(\x0b\x32\x15.loop.v1.Sha256Digestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.v1.development_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVELOPMENTDATASETREFERENCE']._serialized_start=65
  _globals['_DEVELOPMENTDATASETREFERENCE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
