# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/v1/research_common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/v1/research_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dloop/v1/research_common.proto\x12\x07loop.v1\x1a\x14loop/v1/common.proto\"\xe0\x02\n\x1dResearchProvenanceFingerprint\x12\x31\n\x12source_code_sha256\x18\x01 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12\x37\n\x18operator_registry_sha256\x18\x02 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12\x33\n\x14\x63onfiguration_sha256\x18\x03 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12\x33\n\x14\x64\x61ta_manifest_sha256\x18\x04 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12\x36\n\x17trading_calendar_sha256\x18\x05 \x01(\x0b\x32\x15.loop.v1.Sha256Digest\x12\x31\n\x12\x65nvironment_sha256\x18\x06 \x01(\x0b\x32\x15.loop.v1.Sha256Digest*^\n\x10ReturnDefinition\x12!\n\x1dRETURN_DEFINITION_UNSPECIFIED\x10\x00\x12\'\n#RETURN_DEFINITION_SIMPLE_NAV_RETURN\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.v1.research_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETURNDEFINITION']._serialized_start=419
  _globals['_RETURNDEFINITION']._serialized_end=513
  _globals['_RESEARCHPROVENANCEFINGERPRINT']._serialized_start=65
  _globals['_RESEARCHPROVENANCEFINGERPRINT']._serialized_end=417
# @@protoc_insertion_point(module_scope)
