# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loop/v1/stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'loop/v1/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from loop.v1 import common_pb2 as loop_dot_v1_dot_common__pb2
from loop.v1 import model_pb2 as loop_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14loop/v1/stream.proto\x12\x07loop.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14loop/v1/common.proto\x1a\x13loop/v1/model.proto\"B\n\rStreamStarted\x12\x31\n\rresolution_id\x18\x01 \x01(\x0b\x32\x1a.loop.v1.ModelResolutionId\"\x19\n\tTextDelta\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0eReasoningDelta\x12\x0c\n\x04text\x18\x01 \x01(\t\"Y\n\rToolCallDelta\x12\x14\n\x0ctool_call_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x1f\n\x17\x61rguments_json_fragment\x18\x03 \x01(\x0c\"\xad\x01\n\x0c\x43ontentDelta\x12\x15\n\rcontent_index\x18\x01 \x01(\r\x12\"\n\x04text\x18\x02 \x01(\x0b\x32\x12.loop.v1.TextDeltaH\x00\x12,\n\treasoning\x18\x03 \x01(\x0b\x32\x17.loop.v1.ReasoningDeltaH\x00\x12+\n\ttool_call\x18\x04 \x01(\x0b\x32\x16.loop.v1.ToolCallDeltaH\x00\x42\x07\n\x05\x64\x65lta\"1\n\x0bUsageUpdate\x12\"\n\x05usage\x18\x01 \x01(\x0b\x32\x13.loop.v1.ModelUsage\";\n\x0fStreamCompleted\x12(\n\x08response\x18\x01 \x01(\x0b\x32\x16.loop.v1.ModelResponse\"\xdc\x02\n\x10ModelStreamEvent\x12&\n\nrequest_id\x18\x01 \x01(\x0b\x32\x12.loop.v1.RequestId\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12.\n\nemitted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x07started\x18\x04 \x01(\x0b\x32\x16.loop.v1.StreamStartedH\x00\x12.\n\rcontent_delta\x18\x05 \x01(\x0b\x32\x15.loop.v1.ContentDeltaH\x00\x12,\n\x0cusage_update\x18\x06 \x01(\x0b\x32\x14.loop.v1.UsageUpdateH\x00\x12-\n\tcompleted\x18\x07 \x01(\x0b\x32\x18.loop.v1.StreamCompletedH\x00\x42\x07\n\x05\x65ventJ\x04\x08\x08\x10\tJ\x04\x08\t\x10\nR\tcancelledR\x06\x66\x61iledb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loop.v1.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMSTARTED']._serialized_start=109
  _globals['_STREAMSTARTED']._serialized_end=175
  _globals['_TEXTDELTA']._serialized_start=177
  _globals['_TEXTDELTA']._serialized_end=202
  _globals['_REASONINGDELTA']._serialized_start=204
  _globals['_REASONINGDELTA']._serialized_end=234
  _globals['_TOOLCALLDELTA']._serialized_start=236
  _globals['_TOOLCALLDELTA']._serialized_end=325
  _globals['_CONTENTDELTA']._serialized_start=328
  _globals['_CONTENTDELTA']._serialized_end=501
  _globals['_USAGEUPDATE']._serialized_start=503
  _globals['_USAGEUPDATE']._serialized_end=552
  _globals['_STREAMCOMPLETED']._serialized_start=554
  _globals['_STREAMCOMPLETED']._serialized_end=613
  _globals['_MODELSTREAMEVENT']._serialized_start=616
  _globals['_MODELSTREAMEVENT']._serialized_end=964
# @@protoc_insertion_point(module_scope)
