# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from loop.discovery.v1 import service_pb2 as loop_dot_discovery_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loop/discovery/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryServiceStub:
    """DiscoveryService has no holdout method, grant, period, approval, or protected
    dataset input. Its runtime principal is never issued a holdout capability.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartDiscovery = channel.unary_unary(
                '/loop.discovery.v1.DiscoveryService/StartDiscovery',
                request_serializer=loop_dot_discovery_dot_v1_dot_service__pb2.StartDiscoveryRequest.SerializeToString,
                response_deserializer=loop_dot_discovery_dot_v1_dot_service__pb2.StartDiscoveryResponse.FromString,
                _registered_method=True)


class DiscoveryServiceServicer:
    """DiscoveryService has no holdout method, grant, period, approval, or protected
    dataset input. Its runtime principal is never issued a holdout capability.
    """

    def StartDiscovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartDiscovery': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDiscovery,
                    request_deserializer=loop_dot_discovery_dot_v1_dot_service__pb2.StartDiscoveryRequest.FromString,
                    response_serializer=loop_dot_discovery_dot_v1_dot_service__pb2.StartDiscoveryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.discovery.v1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.discovery.v1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService:
    """DiscoveryService has no holdout method, grant, period, approval, or protected
    dataset input. Its runtime principal is never issued a holdout capability.
    """

    @staticmethod
    def StartDiscovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.discovery.v1.DiscoveryService/StartDiscovery',
            loop_dot_discovery_dot_v1_dot_service__pb2.StartDiscoveryRequest.SerializeToString,
            loop_dot_discovery_dot_v1_dot_service__pb2.StartDiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
